// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace batatinha
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class BatatinhaDisponivel : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"BatatinhaDisponivel\",\"namespace\":\"batatinha\",\"fields\":[{" +
				"\"name\":\"tipo\",\"type\":\"string\"},{\"name\":\"quantidade\",\"type\":\"int\"}]}");
		private string _tipo;
		private int _quantidade;
		public virtual Schema Schema
		{
			get
			{
				return BatatinhaDisponivel._SCHEMA;
			}
		}
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				this._tipo = value;
			}
		}
		public int quantidade
		{
			get
			{
				return this._quantidade;
			}
			set
			{
				this._quantidade = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.tipo;
			case 1: return this.quantidade;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.tipo = (System.String)fieldValue; break;
			case 1: this.quantidade = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
